version: '3'
services:
  server:
    container_name: server
    command: python /app/server.py
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    networks:
      - mynetwork
    ports:
      - 5000:5000
    environment:
    - "PYTHONUNBUFFERED=1"

  client:
    image: python:3.9
    container_name: client
    command: python /app/client.py
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    networks:
      - mynetwork
    depends_on: 
      - server
    ports:
      - 5001:5001

networks:
  mynetwork: 